/**
 * generate_fa_subset.js
 *
 * Script one-shot qui lit meta/ressources/regular_icons.js et génère un fichier
 * js/fa-subset.js ne contenant que les icônes réellement
 * utilisées dans le projet.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '../..');
const FA_SOURCE = path.join(ROOT, 'meta', 'ressources', 'regular_icons.js');
const OUTPUT_FILE = path.join(ROOT, 'js', 'fa-subset.js');

// Directories to scan for icon usage
const SCAN_DIRS = [
    path.join(ROOT, 'webapps'),
    path.join(ROOT, 'webapps', 'teacher'),
    path.join(ROOT, 'alpha', 'webapps'),
];
const SCAN_FILES = [path.join(ROOT, 'index.html')];

// ── Step 1: Find all icon names used ──
function findUsedIcons() {
    const icons = new Set();
    const regex = /data-fa="([^"]+)"/g;

    function scanFile(filePath) {
        const content = fs.readFileSync(filePath, 'utf-8');
        let match;
        while ((match = regex.exec(content)) !== null) {
            if (!match[1].startsWith('$')) {
                icons.add(match[1]);
            }
        }
    }

    for (const dir of SCAN_DIRS) {
        if (!fs.existsSync(dir)) continue;
        const files = fs.readdirSync(dir).filter(f => f.endsWith('.html'));
        for (const file of files) {
            scanFile(path.join(dir, file));
        }
    }
    for (const file of SCAN_FILES) {
        if (fs.existsSync(file)) scanFile(file);
    }

    // Add commonly used icons from JS if any
    icons.add('circle-check');
    icons.add('circle-xmark');
    icons.add('triangle-exclamation');
    icons.add('circle-info');

    return [...icons].sort();
}


// ── Step 3: Extract icon definitions from the full bundle ──
function extractIconDefinitions(iconNames) {
    const faCode = fs.readFileSync(FA_SOURCE, 'utf-8');
    const extracted = {};
    let missing = [];

    const match = faCode.match(/const icons = (\{[\s\S]*?\});\s*bunker/);
    let allIcons = {};
    if (match) {
        try {
            allIcons = new Function("return " + match[1])();
        } catch(e) {}
    } else {
        const match2 = faCode.match(/var icons = (\{[\s\S]*?\})[;\n]*\s*bunker/);
        if(match2) {
            try {
                allIcons = new Function("return " + match2[1])();
            } catch(e) {}
        }
    }

    for (const name of iconNames) {
        if (allIcons[name]) {
            extracted[name] = JSON.stringify(allIcons[name]);
        } else {
            missing.push(name);
        }
    }

    if (missing.length > 0) {
        console.warn('⚠️  ' + missing.length + ' icons not found: ' + missing.join(', '));
    }
    return extracted;
}

// ── Step 4: Generate the subset file ──
function generateSubset(iconNames, iconDefinitions) {
    const iconEntries = iconNames
        .filter(name => iconDefinitions[name])
        .map(name => {
            return '  "' + name + '": ' + iconDefinitions[name] + ',';
        })
        .join('\n');

    const output = `/**
 * fa-subset.js — Subset of FontAwesome Pro 7 Icons
 *
 * Auto-generated by scripts/generate_fa_subset.js
 * Contains only the ${Object.keys(iconDefinitions).length} icons used in this project.
 */
(function(root) {
  "use strict";

  const icons = {
${iconEntries}
  };

  function createIcons({ attrs = {}, nameAttr = "data-fa" } = {}) {
    const elements = document.querySelectorAll("[" + nameAttr + "]");
    elements.forEach(el => {
      const name = el.getAttribute(nameAttr);
      if (!name) return;
      const iconData = icons[name];
      if (!iconData) {
        console.warn("fa-subset: icon '" + name + "' not found in subset.");
        return;
      }

      // FA icon data is: [width, height, aliases, unicode, path]
      const width = iconData[0];
      const height = iconData[1];
      const pathData = iconData[4];

      const existingAttrs = {};
      Array.from(el.attributes).forEach(a => { existingAttrs[a.name] = a.value; });

      const hasAria = Object.keys(existingAttrs).some(k => k.startsWith("aria-") || k === "role" || k === "title");
      const ariaAttrs = hasAria ? {} : { "aria-hidden": "true" };

      const mergedAttrs = {
        xmlns: "http://www.w3.org/2000/svg",
        viewBox: "0 0 " + width + " " + height,
        fill: "currentColor",
        ...ariaAttrs,
        ...attrs,
        ...existingAttrs
      };

      // Keep data-fa for reference
      mergedAttrs["data-fa"] = name;

      // Build class
      const classes = ["fa-icon", "fa-" + name];
      if (existingAttrs.class) classes.push(existingAttrs.class);
      if (attrs.class) classes.push(typeof attrs.class === "string" ? attrs.class : attrs.class.join(" "));
      mergedAttrs.class = [...new Set(classes.filter(Boolean))].join(" ").trim();

      const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
      Object.keys(mergedAttrs).forEach(k => svg.setAttribute(k, String(mergedAttrs[k])));

      const pathEl = document.createElementNS("http://www.w3.org/2000/svg", "path");
      pathEl.setAttribute("d", pathData);
      svg.appendChild(pathEl);

      el.parentNode.replaceChild(svg, el);
    });
  }

  // Export
  const fa = { icons, createIcons };
  if (typeof module !== "undefined" && module.exports) {
    module.exports = fa;
  } else {
    root.fa = fa;
  }
})(typeof globalThis !== "undefined" ? globalThis : typeof self !== "undefined" ? self : this);
`;
    return output;
}

// ── Main ──
console.log('🔍 Scanning HTML files for FA icon usage...');
const usedIcons = findUsedIcons();
console.log(`   Found ${usedIcons.length} unique icons: ${usedIcons.join(', ')}`);

console.log('📦 Extracting icon definitions from regular_icons.js...');
const definitions = extractIconDefinitions(usedIcons);
const foundCount = Object.keys(definitions).length;
console.log(`   Extracted ${foundCount}/${usedIcons.length} icon definitions.`);

console.log('✏️  Generating subset file...');
const output = generateSubset(usedIcons, definitions);
fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');
const newSize = fs.statSync(OUTPUT_FILE).size;
console.log(`✅ Written to ${OUTPUT_FILE}`);
console.log(`   Subset:   ${(newSize / 1024).toFixed(0)} Ko`);
