const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const FA_SOURCE = path.join(ROOT, 'js', 'regular_icons.js');
const OUTPUT_FILE = path.join(ROOT, 'js', 'lucide-subset.js');

// Directories to scan for icon usage
const SCAN_DIRS = [
    path.join(ROOT, 'webapps'),
    path.join(ROOT, 'ressources'),
    path.join(ROOT, 'alpha', 'webapps'),
];
const SCAN_FILES = [path.join(ROOT, 'index.html')];

const mapping = {
  'arrow-right-left': 'arrow-right-arrow-left',
  'bar-chart-2': 'chart-bar',
  'bot': 'robot',
  'boxes': 'boxes-stacked',
  'check-circle': 'circle-check',
  'cpu': 'microchip',
  'delete': 'delete-left',
  'dices': 'dice',
  'edit-3': 'pen-to-square',
  'eye-off': 'eye-slash',
  'flip-horizontal': 'left-right',
  'gamepad-2': 'gamepad',
  'git-merge': 'code-merge',
  'hand-grab': 'hand-back-fist',
  'library': 'book-open-reader',
  'message-circle': 'comment',
  'monitor': 'display',
  'network': 'network-wired',
  'package': 'box',
  'printer': 'print',
  'radio-receiver': 'radio',
  'rotate-ccw': 'rotate-left',
  'search': 'magnifying-glass',
  'settings': 'gear',
  'settings-2': 'sliders',
  'target': 'bullseye',
  'trash-2': 'trash-can',
  'type': 'font',
  'volume-2': 'volume-high',
  'volume-x': 'volume-xmark'
};

// ── Step 1: Find all icon names used ──
function findUsedIcons() {
    const icons = new Set();
    const regex = /data-lucide="([^"]+)"/g;

    function scanFile(filePath) {
        const content = fs.readFileSync(filePath, 'utf-8');
        let match;
        while ((match = regex.exec(content)) !== null) {
            if (!match[1].startsWith('$')) {
                icons.add(match[1]);
            }
        }
    }

    for (const dir of SCAN_DIRS) {
        if (!fs.existsSync(dir)) continue;
        const files = fs.readdirSync(dir).filter(f => f.endsWith('.html'));
        for (const file of files) {
            scanFile(path.join(dir, file));
        }
    }
    for (const file of SCAN_FILES) {
        if (fs.existsSync(file)) scanFile(file);
    }

    return [...icons].sort();
}

function extractIconDefinitionsRegex(iconNames, sourceCode) {
    const extracted = {};
    for (const lucideName of iconNames) {
        const faName = mapping[lucideName] || lucideName;
        const escapedName = faName.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
        const re = new RegExp(`"${escapedName}"\\s*:\\s*\\[\\s*(\\d+)\\s*,\\s*(\\d+)\\s*,\\s*\\[(.*?)\\]\\s*,\\s*"([^"]+)"\\s*,\\s*"([^"]+)"\\s*\\]`);
        const match = sourceCode.match(re);
        if (match) {
            const [, width, height, aliasesStr, unicode, pathData] = match;
            extracted[lucideName] = {
                width: parseInt(width, 10),
                height: parseInt(height, 10),
                pathData: pathData
            };
        } else {
            console.warn(`Icon ${lucideName} (FA: ${faName}) not found in FA source.`);
        }
    }
    return extracted;
}

function toPascalCase(str) {
    return str.replace(/(^|-)([a-z0-9])/g, (_, __, c) => c.toUpperCase());
}

function generateSubset(iconNames, iconDefinitions) {
    const iconEntries = iconNames
        .filter(name => iconDefinitions[name])
        .map(name => {
            const def = iconDefinitions[name];
            return `  "${toPascalCase(name)}": {
    viewBox: "0 0 ${def.width} ${def.height}",
    children: [["path", { "d": "${def.pathData}" }]]
  }`;
        })
        .join(',\n');

    const output = `/**
 * fa-subset.js — FontAwesome Pro Subset (API compatible with Lucide)
 * 
 * Auto-generated by scripts/generate_lucide_subset.js
 * Contains only the ${Object.keys(iconDefinitions).length} icons used in this project.
 */
(function(root) {
  "use strict";

  const defaultAttrs = {
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor"
  };

  function createSvgElement([tag, attrs, children]) {
    const el = document.createElementNS("http://www.w3.org/2000/svg", tag);
    Object.keys(attrs).forEach(k => el.setAttribute(k, String(attrs[k])));
    if (children) children.forEach(c => el.appendChild(createSvgElement(c)));
    return el;
  }

  function toPascalCase(str) {
    return str.replace(/(^|-)([a-z0-9])/g, (_, __, c) => c.toUpperCase());
  }

  const icons = {
${iconEntries}
  };

  function createIcons({ attrs = {}, nameAttr = "data-lucide" } = {}) {
    const elements = document.querySelectorAll("[" + nameAttr + "]");
    elements.forEach(el => {
      const name = el.getAttribute(nameAttr);
      if (!name) return;
      const pascal = toPascalCase(name);
      const iconData = icons[pascal];
      if (!iconData) {
        console.warn("fa-subset: icon '" + name + "' not found in subset.");
        return;
      }

      const existingAttrs = {};
      Array.from(el.attributes).forEach(a => { existingAttrs[a.name] = a.value; });
      
      const hasAria = Object.keys(existingAttrs).some(k => k.startsWith("aria-") || k === "role" || k === "title");
      const ariaAttrs = hasAria ? {} : { "aria-hidden": "true" };
      
      const mergedAttrs = {
        ...defaultAttrs,
        "data-lucide": name,
        viewBox: iconData.viewBox,
        ...ariaAttrs,
        ...attrs,
        ...existingAttrs
      };

      // Remove stroke attributes that might mess up filled FontAwesome icons
      delete mergedAttrs.stroke;
      delete mergedAttrs['stroke-width'];
      delete mergedAttrs['stroke-linecap'];
      delete mergedAttrs['stroke-linejoin'];

      // Build class
      const classes = ["lucide", "lucide-" + name, "fa-icon"];
      if (existingAttrs.class) classes.push(existingAttrs.class);
      if (attrs.class) classes.push(typeof attrs.class === "string" ? attrs.class : attrs.class.join(" "));
      mergedAttrs.class = [...new Set(classes.filter(Boolean))].join(" ").trim();

      const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
      Object.keys(mergedAttrs).forEach(k => svg.setAttribute(k, mergedAttrs[k]));

      iconData.children.forEach(c => svg.appendChild(createSvgElement(c)));

      el.parentNode.replaceChild(svg, el);
    });
  }

  // Export
  const lucide = { icons, createIcons };
  if (typeof module !== "undefined" && module.exports) {
    module.exports = lucide;
  } else {
    root.lucide = lucide;
  }
})(typeof globalThis !== "undefined" ? globalThis : typeof self !== "undefined" ? self : this);
`;
    return output;
}

const usedIcons = findUsedIcons();
const faSource = fs.readFileSync(FA_SOURCE, 'utf-8');
const definitions = extractIconDefinitionsRegex(usedIcons, faSource);
const output = generateSubset(usedIcons, definitions);
fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');
console.log("Written to " + OUTPUT_FILE);
